FROM arm32v6/httpd:2.4-alpine
LABEL maintainer="mukul.dharwadkar@gmail.com"
RUN apk update && apk upgrade && apk add vim php7 php7-fpm php7-opcache php7-apache2 php7-mysqli

RUN sed -i '/LoadModule rewrite_module/s/^#//g' /usr/local/apache2/conf/httpd.conf

RUN { \
  echo 'IncludeOptional conf.d/*.conf'; \
} >> /usr/local/apache2/conf/httpd.conf \
  && mkdir /usr/local/apache2/conf.d

EXPOSE 80 22

#CMD ["apache2ctl", "-D", "FOREGROUND"]
